project-includes = [
    "app",
    "scripts",
    "tests",
    "cli.py",
    "conftest.py",
]
project-excludes = ["venv", "data"]
search-path = ["."]
python-platform = "linux"
python-version = "3.14"
preset = "strict"
[errors]
explicit-any = true
no-any-return = true
