import type { JudgeQuestion, Kind, Phase } from "./types.ts";

export const QUESTION_BANK_VERSION = "4";

function q(id: string, phase: Phase, instruction: string, kind: Kind, critical: boolean): JudgeQuestion {
 return { id, phase, instruction, kind, critical };
}

const P = "pass_when_yes" as const;
const T = "trigger_when_yes" as const;

export const QUESTION_BANK: Record<string, JudgeQuestion> = {
 E01: q("E01", "evidence", "The evidence directly bears on the claim being evaluated.", P, true),
 E02: q("E02", "evidence", "The cited passage actually supports or contradicts the claim rather than merely mentioning the same topic, company, or entities.", P, true),
 E03: q("E03", "evidence", "The evidence is specific enough to support the directional wording used in the claim.", P, false),
 E04: q("E04", "evidence", "The evidence is specific enough to support any magnitude wording used in the claim.", P, false),
 E05: q("E05", "evidence", "The evidence is specific enough to support any timing wording used in the claim.", P, false),
 E06: q("E06", "evidence", "The evidence addresses the research objective rather than an adjacent but materially different question.", P, false),
 E07: q("E07", "evidence", "The source is appropriate for the strength of the claim being made.", P, false),
 E08: q("E08", "evidence", "The claim does not generalize materially beyond what the evidence establishes.", P, false),
 E09: q("E09", "evidence", "Any inference drawn from the evidence is clearly distinguishable from an observed fact.", P, false),
 E10: q("E10", "evidence", "This evidence adds materially new information beyond evidence already associated with the claim.", P, false),
 E11: q("E11", "evidence", "The evidence contains information useful to resolving the current branch rather than background with no decision value.", P, false),
 E12: q("E12", "evidence", "The evidence would cause a reasonable researcher to update their understanding of the claim.", P, false),
 E13: q("E13", "evidence", "The evidence is sufficiently unambiguous to be used in analysis without materially changing its meaning.", P, false),
 E14: q("E14", "evidence", "The evidence is not being used out of context in a way that changes its implication.", P, true),
 E15: q("E15", "evidence", "The evidence meaningfully informs the original user's question.", P, false),
 E16: q("E16", "evidence", "This evidence should count toward resolving the claim.", P, true),
 C01: q("C01", "claim", "The current evidence materially supports this claim.", P, true),
 C02: q("C02", "claim", "The current evidence materially contradicts this claim.", T, true),
 C03: q("C03", "claim", "The current evidence is sufficient to state the directional conclusion of this claim to the user.", P, true),
 C04: q("C04", "claim", "The current evidence is sufficient to state this claim as an observed fact rather than an inference.", P, false),
 C05: q("C05", "claim", "The current evidence is sufficient to state this claim as an inference if it is clearly labeled as one.", P, false),
 C06: q("C06", "claim", "The current evidence is insufficient to state this claim even as a bounded inference.", T, true),
 C07: q("C07", "claim", "The causal relationship asserted by this claim is actually supported by the evidence.", P, false),
 C08: q("C08", "claim", "A materially plausible alternative explanation remains unresolved.", T, false),
 C09: q("C09", "claim", "The evidence supports the magnitude or materiality language attached to this claim.", P, false),
 C10: q("C10", "claim", "The evidence supports the timing or horizon attached to this claim.", P, false),
 C11: q("C11", "claim", "The evidence supports the downside mechanism asserted by this claim.", P, false),
 C12: q("C12", "claim", "The evidence supports the resilience or upside mechanism asserted by this claim.", P, false),
 C13: q("C13", "claim", "Material counterevidence has been considered before resolving this claim.", P, true),
 C14: q("C14", "claim", "The remaining uncertainty around this claim can be honestly communicated without making the answer misleading.", P, false),
 C15: q("C15", "claim", "Resolving this claim materially helps answer the user's original question.", P, false),
 C16: q("C16", "claim", "This claim can be closed for the current research run without pretending to know more than the evidence shows.", P, false),
 V01: q("V01", "coverage", "The research branch map covers all materially different parts of the user's question.", P, true),
 V02: q("V02", "coverage", "All material companies, entities, or counterparties identified by the research have been investigated.", P, true),
 V03: q("V03", "coverage", "All material direct relationship channels have been investigated.", P, true),
 V04: q("V04", "coverage", "Material indirect or second-order relationship channels have been investigated where relevant.", P, true),
 V05: q("V05", "coverage", "The relevant time horizon has been investigated.", P, true),
 V06: q("V06", "coverage", "The most recent materially relevant disclosures available within the requested as-of boundary have been considered.", P, true),
 V07: q("V07", "coverage", "Historical context needed to interpret the current evidence has been investigated where material.", P, true),
 V08: q("V08", "coverage", "The relevant filing/document categories for this question have been searched where appropriate.", P, true),
 V09: q("V09", "coverage", "Material footnotes, exhibits, contracts, schedules, or attachments have been investigated where relevant.", P, true),
 V10: q("V10", "coverage", "Material counterparty or cross-company evidence has been investigated where it could change the answer.", P, true),
 V11: q("V11", "coverage", "Ownership, equity, investment, or capital relationships have been investigated where material.", P, true),
 V12: q("V12", "coverage", "Revenue, customer, commercial, licensing, or demand relationships have been investigated where material.", P, true),
 V13: q("V13", "coverage", "Supplier, infrastructure, capacity, manufacturing, or operational dependencies have been investigated where material.", P, true),
 V14: q("V14", "coverage", "Financing, guarantees, credit support, liabilities, commitments, or contingent obligations have been investigated where material.", P, true),
 V15: q("V15", "coverage", "Legal, regulatory, litigation, or government exposure has been investigated where material.", P, true),
 V16: q("V16", "coverage", "Management guidance, risk disclosures, and stated strategic dependencies have been investigated where material.", P, true),
 V17: q("V17", "coverage", "The research actively looked for evidence that would contradict its emerging conclusion.", P, true),
 V18: q("V18", "coverage", "Material negative evidence or evidence of absence has been investigated rather than only supportive evidence.", P, true),
 V19: q("V19", "coverage", "The remaining unsearched routes are unlikely to contain evidence that would materially change the answer.", P, true),
 V20: q("V20", "coverage", "The current coverage is sufficient to answer the user's question at an honest level of specificity.", P, true),
 N01: q("N01", "continuation", "A material unresolved question remains after the current research.", T, true),
 N02: q("N02", "continuation", "At least one unsearched route is reasonably likely to contain material evidence.", T, true),
 N03: q("N03", "continuation", "Additional research is likely to materially improve the quality of the answer.", T, true),
 N04: q("N04", "continuation", "Additional research is reasonably likely to change the conclusion or the level of specificity that can be supported.", T, true),
 N05: q("N05", "continuation", "The current unresolved items can be represented honestly as uncertainty without further research.", P, true),
 N06: q("N06", "continuation", "Research can stop now without creating a materially misleading impression of completeness.", P, true),
 N07: q("N07", "candidate", "This proposed investigation directly addresses a material unresolved question.", P, true),
 N08: q("N08", "candidate", "This proposed investigation is likely to produce materially new evidence.", P, true),
 N09: q("N09", "candidate", "This proposed investigation is meaningfully different from research already completed.", P, true),
 N10: q("N10", "candidate", "This proposed investigation is likely to improve the supported resolution of the answer.", P, true),
 N11: q("N11", "candidate", "This proposed investigation is likely to help resolve a material contradiction or uncertainty.", P, false),
 N12: q("N12", "candidate", "This proposed investigation is sufficiently targeted to justify execution.", P, true),
 N13: q("N13", "candidate", "The execution task faithfully implements the proposed investigation and does not materially expand or redirect its scope.", P, true),
 Q01: q("Q01", "role_output", "The output addresses all material parts of the assigned research question.", P, true),
 Q02: q("Q02", "role_output", "The output reflects all materially important evidence relevant to its role.", P, true),
 Q03: q("Q03", "role_output", "The output does not omit materially important contradictory evidence.", P, true),
 Q04: q("Q04", "role_output", "Every substantive factual claim is supported by the evidence cited for that claim.", P, true),
 Q05: q("Q05", "role_output", "Observed facts and inferences are clearly distinguished.", P, true),
 Q06: q("Q06", "role_output", "Material uncertainty is explicitly acknowledged rather than hidden.", P, true),
 Q07: q("Q07", "role_output", "The certainty of the language is proportionate to the strength of the evidence.", P, true),
 Q08: q("Q08", "role_output", "Magnitude language is proportionate to what the evidence actually establishes.", P, false),
 Q09: q("Q09", "role_output", "The reasoning explains how evidence leads to conclusions rather than merely listing facts.", P, false),
 Q10: q("Q10", "role_output", "The output explains the important first-order effects implied by the evidence.", P, false),
 Q11: q("Q11", "role_output", "The output explains material second-order effects where the evidence reasonably supports them.", P, false),
 Q12: q("Q12", "role_output", "The output identifies what evidence or future events would materially change its conclusion.", P, false),
 Q13: q("Q13", "role_output", "The bottom-line conclusion actually answers the user's question.", P, true),
 Q14: q("Q14", "role_output", "The reasoning is internally coherent and does not contradict itself.", P, true),
 Q15: q("Q15", "role_output", "The output contains no material unsupported leap from evidence to conclusion.", P, true),
 Q16: q("Q16", "role_output", "The output avoids unnecessary repetition that obscures the decision-relevant information.", P, false),
 Q17: q("Q17", "role_output", "The output is clear enough that a user can distinguish established facts, interpretations, and unknowns.", P, false),
 Q18: q("Q18", "role_output", "The output accurately communicates the limitations of the evidence and research scope.", P, true),
 S01: q("S01", "role_output", "Stockbot fairly weights the evidence instead of selectively emphasizing only positive or negative material.", P, true),
 S02: q("S02", "role_output", "Stockbot does not create artificial balance when the evidence materially favors one interpretation.", P, true),
 S03: q("S03", "committee", "Stockbot clearly distinguishes genuine committee consensus from genuine disagreement.", P, true),
 S04: q("S04", "role_output", "Stockbot's base-case conclusion follows the strongest overall evidence rather than the most dramatic scenario.", P, true),
 S05: q("S05", "role_output", "Stockbot considers both material resilience/upside and downside channels before settling the base case.", P, true),
 S06: q("S06", "role_output", "Stockbot's proposed follow-up questions map to actual unresolved material uncertainties.", P, true),
 B01: q("B01", "role_output", "Bullbot identifies the strongest resilience or upside interpretation that the evidence can genuinely support.", P, true),
 B02: q("B02", "role_output", "Bullbot does not manufacture optimism unsupported by the evidence.", P, true),
 B03: q("B03", "role_output", "If material downside evidence exists, Bullbot acknowledges it and explains how it constrains the bullish case; otherwise this criterion is satisfied.", P, true),
 B04: q("B04", "role_output", "Bullbot explains the evidence-backed mechanisms through which damage could be limited, reversed, absorbed, or offset.", P, true),
 B05: q("B05", "role_output", "Bullbot identifies the conditions or catalysts required for its favorable interpretation to hold.", P, true),
 B06: q("B06", "role_output", "Bullbot contributes a materially distinct evidence-based perspective rather than merely restating Stockbot positively.", P, true),
 R01: q("R01", "role_output", "Bearbot identifies the strongest downside or contagion interpretation that the evidence can genuinely support.", P, true),
 R02: q("R02", "role_output", "Bearbot does not manufacture pessimism unsupported by the evidence.", P, true),
 R03: q("R03", "role_output", "If material resilience evidence exists, Bearbot acknowledges it and explains how it constrains the bearish case; otherwise this criterion is satisfied.", P, true),
 R04: q("R04", "role_output", "Bearbot explains the evidence-backed mechanisms through which impairment, spillover, or downside could occur.", P, true),
 R05: q("R05", "role_output", "Bearbot identifies the conditions or catalysts required for the adverse interpretation to materialize.", P, true),
 R06: q("R06", "role_output", "Bearbot contributes a materially distinct evidence-based perspective rather than merely restating Stockbot negatively.", P, true),
 F01: q("F01", "committee", "Stockbot, Bullbot, and Bearbot analyzed the same substantive evidence set.", P, true),
 F02: q("F02", "committee", "Collectively, the committee addresses all material claims identified in the research objective.", P, true),
 F03: q("F03", "committee", "If material disagreements exist between committee members, they arise from different evidence interpretations rather than mere tone; if no material disagreement exists, this criterion is satisfied.", P, true),
 F04: q("F04", "committee", "If the evidence genuinely supports competing interpretations, the committee clearly exposes them; if no such competing interpretation exists, this criterion is satisfied.", P, true),
 F05: q("F05", "committee", "Genuine areas of consensus are identifiable across the three outputs.", P, true),
 F06: q("F06", "committee", "No material perspective implied by the evidence is missing from all three committee outputs.", P, true),
 F07: q("F07", "committee", "The committee collectively covers the important base-case, resilience/upside, and downside channels.", P, true),
 F08: q("F08", "committee", "Any requested additional research maps to a real unresolved disagreement or evidence gap.", P, false),
 F09: q("F09", "final", "The final synthesis faithfully represents Stockbot's base case, Bullbot's strongest supported case, and Bearbot's strongest supported case.", P, true),
 F10: q("F10", "final", "The final answer does not state any material conclusion more strongly than the underlying evidence and committee analysis permit.", P, true),
 F11: q("F11", "final", "The final answer explains the key reasoning chain well enough for the user to understand why the conclusion follows.", P, true),
 F12: q("F12", "final", "The final answer is complete enough to answer the original question without hiding material evidence, disagreement, or uncertainty.", P, true),
};

const ids = (prefix: string, from: number, to: number): string[] => {
 const out: string[] = [];
 for (let n = from; n <= to; n++) out.push(`${prefix}${String(n).padStart(2, "0")}`);
 return out;
};

export const PACKS: Record<string, string[]> = {
 evidence: ids("E", 1, 16),
 claim: ids("C", 1, 16),
 coverage: ids("V", 1, 20),
 continuation: ["N01", "N02", "N03", "N04", "N05", "N06"],
 candidate: ["N07", "N08", "N09", "N10", "N11", "N12", "N13"],
 common: ids("Q", 1, 18),
 stockbot: ["S01", "S02", "S04", "S05", "S06"],
 bull: ids("B", 1, 6),
 bear: ids("R", 1, 6),
 committee: ["F01", "F02", "F03", "F04", "F05", "F06", "F07", "F08", "S03"],
 final: ["F09", "F10", "F11", "F12"],
 final_extended: ["Q04", "Q05", "Q06", "Q07", "Q08", "Q09", "Q13", "Q14", "Q15", "Q16", "Q17", "Q18", "F09", "F10", "F11", "F12"],
};
